# Generated by Django 3.2.15 on 2023-01-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=100, verbose_name='Application')),
                ('d_views', models.CharField(max_length=100, verbose_name='views')),
                ('d_url_home', models.CharField(max_length=300, verbose_name='URL')),
            ],
        ),
    ]
