# Generated by Django 3.2.15 on 2023-01-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoapplication',
            name='d_portail_name',
            field=models.CharField(default=None, max_length=100, verbose_name='Ref Portail'),
            preserve_default=False,
        ),
    ]
