# Generated by Django 3.2.15 on 2023-03-30 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Supervision', '0010_auto_20230330_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_datetime', models.CharField(blank=True, max_length=100, null=True, verbose_name='Date')),
                ('s_free_memory', models.FloatField(blank=True, max_length=40, null=True, verbose_name='Mémoire Libre')),
                ('s_used_memory', models.FloatField(blank=True, max_length=40, null=True, verbose_name='Mémoire utilisée')),
                ('s_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Supervision.hostlist', verbose_name='Machine')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_datetime', models.CharField(blank=True, max_length=100, null=True, verbose_name='Date')),
                ('m_free_memory', models.FloatField(blank=True, max_length=40, null=True, verbose_name='Mémoire Libre')),
                ('m_used_memory', models.FloatField(blank=True, max_length=40, null=True, verbose_name='Mémoire utilisée')),
                ('m_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Supervision.hostlist', verbose_name='Machine')),
            ],
        ),
    ]
