# Generated by Django 3.2.15 on 2023-01-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('a_precedent_state', models.CharField(max_length=10, verbose_name='Etat précédent')),
                ('a_actual_state', models.CharField(max_length=10, verbose_name='Etat actuel')),
            ],
        ),
        migrations.CreateModel(
            name='HostList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=50, verbose_name='IP')),
                ('h_ip', models.CharField(max_length=50, verbose_name='IP')),
                ('h_status', models.CharField(max_length=10, verbose_name='Etat')),
            ],
        ),
        migrations.CreateModel(
            name='JmeterJmx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('j_scenario_path', models.CharField(max_length=200, verbose_name='Path')),
            ],
        ),
    ]
