# Generated by Django 3.2.15 on 2023-01-26 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supervision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_views', models.CharField(max_length=100, verbose_name='View')),
                ('m_menu_name', models.CharField(max_length=100, verbose_name='Nom menu')),
                ('m_url_view', models.CharField(max_length=100, verbose_name='URL')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='a_host',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='h_machine', to='Supervision.hostlist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='a_scenario_jmx',
            field=models.ManyToManyField(related_name='j_jmx', to='Supervision.JmeterJmx'),
        ),
    ]
