# Generated by Django 3.2.15 on 2023-01-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supervision', '0002_auto_20230126_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='m_href',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='HREF'),
        ),
        migrations.AddField(
            model_name='menus',
            name='m_is_tab',
            field=models.BooleanField(default=False, verbose_name='IsOnglet'),
        ),
        migrations.AlterField(
            model_name='menus',
            name='m_menu_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom menu'),
        ),
        migrations.AlterField(
            model_name='menus',
            name='m_url_view',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='URL'),
        ),
    ]
