# Generated by Django 3.2.15 on 2023-02-09 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supervision', '0004_delete_menus'),
    ]

    operations = [
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_name', models.CharField(blank=True, default='Unknown', max_length=100, null=True, unique=True, verbose_name='Nom')),
                ('o_version', models.CharField(blank=True, default='NA', max_length=10, null=True, verbose_name='Version OS')),
            ],
        ),
        migrations.CreateModel(
            name='TypeServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(blank=True, default='Unknown', max_length=100, null=True, unique=True, verbose_name='Nom')),
                ('t_version_server', models.CharField(blank=True, default='NA', max_length=10, null=True, verbose_name='Version Serveur')),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='a_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h_machine', to='Supervision.hostlist'),
        ),
        migrations.AlterField(
            model_name='hostlist',
            name='h_name',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='hostlist',
            name='h_os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='o_os_installed', to='Supervision.os', verbose_name='OS'),
        ),
        migrations.AddField(
            model_name='hostlist',
            name='h_type_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_server_installed', to='Supervision.typeserver', verbose_name='Serveur'),
        ),
    ]
