# Generated by Django 3.2.15 on 2023-02-14 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supervision', '0007_auto_20230214_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='a_scenario_jmx',
        ),
        migrations.AddField(
            model_name='application',
            name='a_scenario_jmx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='j_jmx', to='Supervision.jmeterjmx'),
        ),
    ]
