# Generated by Django 3.2.15 on 2023-03-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supervision', '0008_auto_20230214_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='a_date_last_KO',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date dernier KO'),
        ),
        migrations.AddField(
            model_name='application',
            name='a_last_ko_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Durée dernier KO'),
        ),
    ]
