# Generated by Django 3.2.15 on 2023-03-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supervision', '0009_auto_20230314_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostlist',
            name='h_total_memory',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Mémoire totale'),
        ),
        migrations.AddField(
            model_name='hostlist',
            name='h_total_swap',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Swap total'),
        ),
    ]
